Adapt to coq/coq#15945
For some reason compilation started failing with
~~~
File "plugin/lib.ml", line 1:
Error: The files /builds/coq/coq/_install_ci/lib/coq-core/vernac/declare.cmi
       and plugin/lib.cmi make inconsistent assumptions over interface Lib
~~~
so we rename plugin/lib